version: '3.8'

services:
  telegram_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: telegram_bot
    env_file: .env
    network_mode: host

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
